"""make_profile_fields_nullable_for_simplified_signup

Revision ID: 117d9e2d09f8
Revises: 20250122_0001
Create Date: 2025-09-21 18:28:04.144238

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = "117d9e2d09f8"
down_revision = "20250122_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Inquiry")
    op.drop_table("feedback30Jan")
    op.alter_column("devotees", "date_of_birth", existing_type=sa.DATE(), nullable=True)
    op.alter_column(
        "devotees",
        "marital_status",
        existing_type=mysql.ENUM("SINGLE", "MARRIED", "DIVORCED", "WIDOWED", "SEPARATED", "OTHERS"),
        nullable=True,
    )
    op.alter_column(
        "devotees", "country_code", existing_type=mysql.VARCHAR(length=5), nullable=True
    )
    op.alter_column(
        "devotees",
        "mobile_number",
        existing_type=mysql.VARCHAR(length=15),
        nullable=True,
    )
    op.alter_column(
        "devotees",
        "father_name",
        existing_type=mysql.VARCHAR(length=127),
        nullable=True,
    )
    op.alter_column(
        "devotees",
        "mother_name",
        existing_type=mysql.VARCHAR(length=127),
        nullable=True,
    )
    op.drop_index("ix_devotees_verification_token", table_name="devotees")
    op.create_index(op.f("ix_devotees_id"), "devotees", ["id"], unique=False)
    op.alter_column(
        "users",
        "password_hash",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=mysql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    op.drop_index("email", table_name="users")
    op.drop_index("ix_users_verification_token", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_verification_token", "users", ["verification_token"], unique=False)
    op.create_index("email", "users", ["email"], unique=True)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=mysql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=mysql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    op.alter_column(
        "users", "password_hash", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    op.drop_index(op.f("ix_devotees_id"), table_name="devotees")
    op.create_index(
        "ix_devotees_verification_token",
        "devotees",
        ["verification_token"],
        unique=False,
    )
    op.alter_column(
        "devotees",
        "mother_name",
        existing_type=mysql.VARCHAR(length=127),
        nullable=False,
    )
    op.alter_column(
        "devotees",
        "father_name",
        existing_type=mysql.VARCHAR(length=127),
        nullable=False,
    )
    op.alter_column(
        "devotees",
        "mobile_number",
        existing_type=mysql.VARCHAR(length=15),
        nullable=False,
    )
    op.alter_column(
        "devotees",
        "country_code",
        existing_type=mysql.VARCHAR(length=5),
        nullable=False,
    )
    op.alter_column(
        "devotees",
        "marital_status",
        existing_type=mysql.ENUM("SINGLE", "MARRIED", "DIVORCED", "WIDOWED", "SEPARATED", "OTHERS"),
        nullable=False,
    )
    op.alter_column("devotees", "date_of_birth", existing_type=sa.DATE(), nullable=False)
    op.create_table(
        "feedback30Jan",
        sa.Column("ID", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("_sfm_form_submision_time_", mysql.DATETIME(), nullable=True),
        sa.Column("_sfm_visitor_ip_", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("_sfm_unique_id_", mysql.VARCHAR(length=35), nullable=True),
        sa.Column("Name", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("Phone", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.Column("Age", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("SessionRating", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("SeminarPoints", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("quesORsuggestion", mysql.MEDIUMTEXT(), nullable=True),
        sa.Column("send_email_updates", mysql.VARCHAR(length=15), nullable=True),
        sa.Column("_sfm_form_submision_date_", sa.DATE(), nullable=True),
        sa.Column("_sfm_referer_page_", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("_sfm_user_agent_", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("_sfm_visitor_browser_", mysql.VARCHAR(length=100), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
        mysql_collate="utf8mb3_general_ci",
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "Inquiry",
        sa.Column("ID", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("_sfm_form_submision_time_", mysql.DATETIME(), nullable=True),
        sa.Column("_sfm_visitor_ip_", mysql.VARCHAR(length=50), nullable=True),
        sa.Column("_sfm_unique_id_", mysql.VARCHAR(length=35), nullable=True),
        sa.Column("Name", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("Email", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("Phone", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("VisitorMessage", mysql.MEDIUMTEXT(), nullable=True),
        sa.PrimaryKeyConstraint("ID"),
        mysql_collate="utf8mb3_general_ci",
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
